@InfraFlowSculptor.Api_HostAddress = http://localhost:5257

GET {{InfraFlowSculptor.Api_HostAddress}}/alive
Accept: application/json

###

GET {{InfraFlowSculptor.Api_HostAddress}}/v1/version
Accept: application/json

###

GET {{InfraFlowSculptor.Api_HostAddress}}/v1/nope
Accept: application/json
