<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>d536607f-46fd-453a-ae41-98db9960270c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.Azure.Storage" />
    <PackageReference Include="Aspire.Hosting.Azure.ServiceBus" />
    <PackageReference Include="Aspire.Hosting.Redis" />
    <PackageReference Include="Aspire.Hosting.Keycloak" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.MailPit" />
    <PackageReference Include="Aspire.Hosting.JavaScript" />
    <PackageReference Include="AzureKeyVaultEmulator.Aspire.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InfraFlowSculptor.Api\InfraFlowSculptor.Api.csproj" />
    <ProjectReference Include="..\InfraFlowSculptor.Worker\InfraFlowSculptor.Worker.csproj" />
  </ItemGroup>

</Project>
