<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>InfraFlowSculptor.Application</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\InfraFlowSculptor.Domain\InfraFlowSculptor.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="ErrorOr" />
      <PackageReference Include="FluentValidation" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
      <PackageReference Include="Mediator.Abstractions" />
      <PackageReference Include="Mediator.SourceGenerator" PrivateAssets="all" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    </ItemGroup>

</Project>
